// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  cameraId: __t.u32().name("camera_id"),
  task: __t.string(),
  classification: __t.string(),
  confidence: __t.string(),
  evidenceRef: __t.string().name("evidence_ref"),
  reviewRequired: __t.bool().name("review_required"),
  reviewed: __t.bool(),
  biometric: __t.bool(),
  createdAt: __t.timestamp().name("created_at"),
});
