// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  faceRecognitionEnabled: __t.bool().name("face_recognition_enabled"),
  emotionalSignalEnabled: __t.bool().name("emotional_signal_enabled"),
  consentRecorded: __t.bool().name("consent_recorded"),
  humanReviewRequired: __t.bool().name("human_review_required"),
  retentionDays: __t.u32().name("retention_days"),
  updatedAt: __t.timestamp().name("updated_at"),
});
