// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  analysisEventId: __t.u32().name("analysis_event_id"),
  cameraId: __t.u32().name("camera_id"),
  evidenceRef: __t.string().name("evidence_ref"),
  sha256: __t.string().name("sha_256"),
  recordedBy: __t.identity().name("recorded_by"),
  createdAt: __t.timestamp().name("created_at"),
  exportedAt: __t.option(__t.timestamp()).name("exported_at"),
  exportedBy: __t.option(__t.identity()).name("exported_by"),
  signedExportRef: __t.option(__t.string()).name("signed_export_ref"),
  signatureAlgorithm: __t.option(__t.string()).name("signature_algorithm"),
});
