// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.8.0 (commit 07aab11f9f256c8a18dd31308ad6ecac40341210).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AcknowledgeEventReducer from "./acknowledge_event_reducer";
import BootstrapAdminReducer from "./bootstrap_admin_reducer";
import EnforceDataRetentionReducer from "./enforce_data_retention_reducer";
import HashEvidenceReducer from "./hash_evidence_reducer";
import LogAnalysisEventReducer from "./log_analysis_event_reducer";
import LogSystemEventReducer from "./log_system_event_reducer";
import MarkEvidenceExportedReducer from "./mark_evidence_exported_reducer";
import RegisterViewerReducer from "./register_viewer_reducer";
import ReportCameraHealthReducer from "./report_camera_health_reducer";
import ReviewAnalysisEventReducer from "./review_analysis_event_reducer";
import SeedDemoReducer from "./seed_demo_reducer";
import SetActorRoleReducer from "./set_actor_role_reducer";
import SetBiometricControlsReducer from "./set_biometric_controls_reducer";
import SetRetentionPolicyReducer from "./set_retention_policy_reducer";
import UpsertCameraReducer from "./upsert_camera_reducer";
import UpsertInstallationReducer from "./upsert_installation_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import ActorsRow from "./actors_table";
import AnalysisEventsRow from "./analysis_events_table";
import AuditLogsRow from "./audit_logs_table";
import BiometricControlsRow from "./biometric_controls_table";
import CameraHealthRow from "./camera_health_table";
import CamerasRow from "./cameras_table";
import EventsRow from "./events_table";
import EvidenceRecordsRow from "./evidence_records_table";
import InstallationsRow from "./installations_table";
import RecordingsRow from "./recordings_table";
import RetentionPoliciesRow from "./retention_policies_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  actors: __table({
    name: 'actors',
    indexes: [
      { accessor: 'identity', name: 'actors_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'role', name: 'actors_role_idx_btree', algorithm: 'btree', columns: [
        'role',
      ] },
    ],
    constraints: [
      { name: 'actors_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, ActorsRow),
  analysisEvents: __table({
    name: 'analysis_events',
    indexes: [
      { accessor: 'biometric', name: 'analysis_events_biometric_idx_btree', algorithm: 'btree', columns: [
        'biometric',
      ] },
      { accessor: 'cameraId', name: 'analysis_events_camera_id_idx_btree', algorithm: 'btree', columns: [
        'cameraId',
      ] },
      { accessor: 'createdAt', name: 'analysis_events_created_at_idx_btree', algorithm: 'btree', columns: [
        'createdAt',
      ] },
      { accessor: 'id', name: 'analysis_events_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'reviewed', name: 'analysis_events_reviewed_idx_btree', algorithm: 'btree', columns: [
        'reviewed',
      ] },
      { accessor: 'task', name: 'analysis_events_task_idx_btree', algorithm: 'btree', columns: [
        'task',
      ] },
    ],
    constraints: [
      { name: 'analysis_events_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AnalysisEventsRow),
  auditLogs: __table({
    name: 'audit_logs',
    indexes: [
      { accessor: 'action', name: 'audit_logs_action_idx_btree', algorithm: 'btree', columns: [
        'action',
      ] },
      { accessor: 'actor', name: 'audit_logs_actor_idx_btree', algorithm: 'btree', columns: [
        'actor',
      ] },
      { accessor: 'createdAt', name: 'audit_logs_created_at_idx_btree', algorithm: 'btree', columns: [
        'createdAt',
      ] },
      { accessor: 'id', name: 'audit_logs_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'audit_logs_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AuditLogsRow),
  biometricControls: __table({
    name: 'biometric_controls',
    indexes: [
      { accessor: 'id', name: 'biometric_controls_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'biometric_controls_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, BiometricControlsRow),
  cameraHealth: __table({
    name: 'camera_health',
    indexes: [
      { accessor: 'cameraId', name: 'camera_health_camera_id_idx_btree', algorithm: 'btree', columns: [
        'cameraId',
      ] },
      { accessor: 'lastCheckedAt', name: 'camera_health_last_checked_at_idx_btree', algorithm: 'btree', columns: [
        'lastCheckedAt',
      ] },
      { accessor: 'maintenanceStatus', name: 'camera_health_maintenance_status_idx_btree', algorithm: 'btree', columns: [
        'maintenanceStatus',
      ] },
    ],
    constraints: [
      { name: 'camera_health_camera_id_key', constraint: 'unique', columns: ['cameraId'] },
    ],
  }, CameraHealthRow),
  cameras: __table({
    name: 'cameras',
    indexes: [
      { accessor: 'id', name: 'cameras_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'installationId', name: 'cameras_installation_id_idx_btree', algorithm: 'btree', columns: [
        'installationId',
      ] },
      { accessor: 'status', name: 'cameras_status_idx_btree', algorithm: 'btree', columns: [
        'status',
      ] },
      { accessor: 'zone', name: 'cameras_zone_idx_btree', algorithm: 'btree', columns: [
        'zone',
      ] },
    ],
    constraints: [
      { name: 'cameras_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CamerasRow),
  events: __table({
    name: 'events',
    indexes: [
      { accessor: 'cameraId', name: 'events_camera_id_idx_btree', algorithm: 'btree', columns: [
        'cameraId',
      ] },
      { accessor: 'id', name: 'events_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'occurredAt', name: 'events_occurred_at_idx_btree', algorithm: 'btree', columns: [
        'occurredAt',
      ] },
      { accessor: 'severity', name: 'events_severity_idx_btree', algorithm: 'btree', columns: [
        'severity',
      ] },
      { accessor: 'type', name: 'events_type_idx_btree', algorithm: 'btree', columns: [
        'type',
      ] },
    ],
    constraints: [
      { name: 'events_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EventsRow),
  evidenceRecords: __table({
    name: 'evidence_records',
    indexes: [
      { accessor: 'analysisEventId', name: 'evidence_records_analysis_event_id_idx_btree', algorithm: 'btree', columns: [
        'analysisEventId',
      ] },
      { accessor: 'cameraId', name: 'evidence_records_camera_id_idx_btree', algorithm: 'btree', columns: [
        'cameraId',
      ] },
      { accessor: 'createdAt', name: 'evidence_records_created_at_idx_btree', algorithm: 'btree', columns: [
        'createdAt',
      ] },
      { accessor: 'id', name: 'evidence_records_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'recordedBy', name: 'evidence_records_recorded_by_idx_btree', algorithm: 'btree', columns: [
        'recordedBy',
      ] },
      { accessor: 'sha256', name: 'evidence_records_sha_256_idx_btree', algorithm: 'btree', columns: [
        'sha256',
      ] },
    ],
    constraints: [
      { name: 'evidence_records_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EvidenceRecordsRow),
  installations: __table({
    name: 'installations',
    indexes: [
      { accessor: 'id', name: 'installations_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'managerId', name: 'installations_manager_id_idx_btree', algorithm: 'btree', columns: [
        'managerId',
      ] },
      { accessor: 'status', name: 'installations_status_idx_btree', algorithm: 'btree', columns: [
        'status',
      ] },
    ],
    constraints: [
      { name: 'installations_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, InstallationsRow),
  recordings: __table({
    name: 'recordings',
    indexes: [
      { accessor: 'cameraId', name: 'recordings_camera_id_idx_btree', algorithm: 'btree', columns: [
        'cameraId',
      ] },
      { accessor: 'id', name: 'recordings_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'startedAt', name: 'recordings_started_at_idx_btree', algorithm: 'btree', columns: [
        'startedAt',
      ] },
    ],
    constraints: [
      { name: 'recordings_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, RecordingsRow),
  retentionPolicies: __table({
    name: 'retention_policies',
    indexes: [
      { accessor: 'cameraId', name: 'retention_policies_camera_id_idx_btree', algorithm: 'btree', columns: [
        'cameraId',
      ] },
      { accessor: 'id', name: 'retention_policies_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'retention_policies_camera_id_key', constraint: 'unique', columns: ['cameraId'] },
      { name: 'retention_policies_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, RetentionPoliciesRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("acknowledge_event", AcknowledgeEventReducer),
  __reducerSchema("bootstrap_admin", BootstrapAdminReducer),
  __reducerSchema("enforce_data_retention", EnforceDataRetentionReducer),
  __reducerSchema("hash_evidence", HashEvidenceReducer),
  __reducerSchema("log_analysis_event", LogAnalysisEventReducer),
  __reducerSchema("log_system_event", LogSystemEventReducer),
  __reducerSchema("mark_evidence_exported", MarkEvidenceExportedReducer),
  __reducerSchema("register_viewer", RegisterViewerReducer),
  __reducerSchema("report_camera_health", ReportCameraHealthReducer),
  __reducerSchema("review_analysis_event", ReviewAnalysisEventReducer),
  __reducerSchema("seed_demo", SeedDemoReducer),
  __reducerSchema("set_actor_role", SetActorRoleReducer),
  __reducerSchema("set_biometric_controls", SetBiometricControlsReducer),
  __reducerSchema("set_retention_policy", SetRetentionPolicyReducer),
  __reducerSchema("upsert_camera", UpsertCameraReducer),
  __reducerSchema("upsert_installation", UpsertInstallationReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.8.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

