// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  cameraId: __t.u32().name("camera_id"),
  startedAt: __t.timestamp().name("started_at"),
  endedAt: __t.timestamp().name("ended_at"),
  durationSeconds: __t.u32().name("duration_seconds"),
  hasMotion: __t.bool().name("has_motion"),
  quality: __t.string(),
});
