// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  cameraId: __t.u32().name("camera_id"),
  retentionDays: __t.u32().name("retention_days"),
  quality: __t.string(),
  recordingMode: __t.string().name("recording_mode"),
  updatedAt: __t.timestamp().name("updated_at"),
});
