// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Actors = __t.object("Actors", {
  identity: __t.identity(),
  displayName: __t.string(),
  role: __t.string(),
  createdAt: __t.timestamp(),
});
export type Actors = __Infer<typeof Actors>;

export const AnalysisEvents = __t.object("AnalysisEvents", {
  id: __t.u32(),
  cameraId: __t.u32(),
  task: __t.string(),
  classification: __t.string(),
  confidence: __t.string(),
  evidenceRef: __t.string(),
  reviewRequired: __t.bool(),
  reviewed: __t.bool(),
  biometric: __t.bool(),
  createdAt: __t.timestamp(),
});
export type AnalysisEvents = __Infer<typeof AnalysisEvents>;

export const AuditLogs = __t.object("AuditLogs", {
  id: __t.u32(),
  actor: __t.identity(),
  action: __t.string(),
  subject: __t.string(),
  details: __t.string(),
  createdAt: __t.timestamp(),
});
export type AuditLogs = __Infer<typeof AuditLogs>;

export const BiometricControls = __t.object("BiometricControls", {
  id: __t.u32(),
  faceRecognitionEnabled: __t.bool(),
  emotionalSignalEnabled: __t.bool(),
  consentRecorded: __t.bool(),
  humanReviewRequired: __t.bool(),
  retentionDays: __t.u32(),
  updatedAt: __t.timestamp(),
});
export type BiometricControls = __Infer<typeof BiometricControls>;

export const Cameras = __t.object("Cameras", {
  id: __t.u32(),
  name: __t.string(),
  location: __t.string(),
  zone: __t.string(),
  protocol: __t.string(),
  streamUrl: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Cameras = __Infer<typeof Cameras>;

export const Events = __t.object("Events", {
  id: __t.u32(),
  cameraId: __t.u32(),
  type: __t.string(),
  severity: __t.string(),
  message: __t.string(),
  occurredAt: __t.timestamp(),
  acknowledged: __t.bool(),
});
export type Events = __Infer<typeof Events>;

export const Recordings = __t.object("Recordings", {
  id: __t.u32(),
  cameraId: __t.u32(),
  startedAt: __t.timestamp(),
  endedAt: __t.timestamp(),
  durationSeconds: __t.u32(),
  hasMotion: __t.bool(),
  quality: __t.string(),
});
export type Recordings = __Infer<typeof Recordings>;

export const RetentionPolicies = __t.object("RetentionPolicies", {
  id: __t.u32(),
  cameraId: __t.u32(),
  retentionDays: __t.u32(),
  quality: __t.string(),
  recordingMode: __t.string(),
  updatedAt: __t.timestamp(),
});
export type RetentionPolicies = __Infer<typeof RetentionPolicies>;

