// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AcknowledgeEventReducer from "../acknowledge_event_reducer";
import BootstrapAdminReducer from "../bootstrap_admin_reducer";
import LogSystemEventReducer from "../log_system_event_reducer";
import RegisterViewerReducer from "../register_viewer_reducer";
import SeedDemoReducer from "../seed_demo_reducer";
import SetActorRoleReducer from "../set_actor_role_reducer";
import SetRetentionPolicyReducer from "../set_retention_policy_reducer";
import UpsertCameraReducer from "../upsert_camera_reducer";

export type AcknowledgeEventParams = __Infer<typeof AcknowledgeEventReducer>;
export type BootstrapAdminParams = __Infer<typeof BootstrapAdminReducer>;
export type LogSystemEventParams = __Infer<typeof LogSystemEventReducer>;
export type RegisterViewerParams = __Infer<typeof RegisterViewerReducer>;
export type SeedDemoParams = __Infer<typeof SeedDemoReducer>;
export type SetActorRoleParams = __Infer<typeof SetActorRoleReducer>;
export type SetRetentionPolicyParams = __Infer<typeof SetRetentionPolicyReducer>;
export type UpsertCameraParams = __Infer<typeof UpsertCameraReducer>;

